backend:
    name: git-gateway
    branch: main

media_folder: 'static/images'
public_folder: '/images'

i18n:
    structure: multiple_files
    locales: [en, es]
    default_locale: en

collections:
    - name: 'pages'
      label: 'Pages'
      folder: 'content'
      create: false
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                i18n: true,
            }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      files:
          - label: 'Homepage'
            name: 'homepage'
            file: 'content/_index.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Hero Title',
                      name: 'hero_title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Hero Subtitle',
                      name: 'hero_subtitle',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }

    - name: 'about'
      label: 'About Page'
      folder: 'content/about'
      create: false
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                i18n: true,
            }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'services'
      label: 'Services Page'
      folder: 'content/services'
      create: false
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                i18n: true,
            }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

    - name: 'contact'
      label: 'Contact Page'
      folder: 'content/contact'
      create: false
      i18n: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string', i18n: true }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                i18n: true,
            }
          - { label: 'Email', name: 'email', widget: 'string', i18n: true }
          - { label: 'Phone', name: 'phone', widget: 'string', i18n: true }
          - { label: 'Address', name: 'address', widget: 'text', i18n: true }
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
