backend:
    name: github
    repo: andr-ew/soulcenter-web # Path to your GitHub repository
    branch: main

media_folder: 'assets/images'
public_folder: '/images'

editor:
    preview: false

i18n:
    structure: multiple_files
    locales: [en, es]
    default_locale: en
collections:
    - name: 'pages'
      label: 'Pages'
      i18n:
          structure: multiple_files
          locales: [en, es]
          default_locale: en
      files:
          - label: 'Homepage'
            name: 'homepage'
            file: 'content/_index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'SEO metatag - description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                      hint: 'not visible on the page, shown on browser tab & in search results',
                  }
                - label: 'About Alicia'
                  name: 'about_alicia'
                  widget: object
                  i18n: true
                  fields:
                      - label: 'Header Photo Left'
                        name: 'header_photo_left'
                        widget: image
                        choose_url: false
                        i18n: duplicate
                      - label: 'Header Photo Left (Alt Text)'
                        name: 'header_photo_left_alt'
                        widget: string
                        i18n: true
                      - label: 'Header Photo Right'
                        name: 'header_photo_right'
                        widget: image
                        choose_url: false
                        i18n: duplicate
                      - label: 'Header Photo Right (Alt Text)'
                        name: 'header_photo_right_alt'
                        widget: string
                        i18n: true
                      - label: 'Content'
                        name: 'content'
                        widget: markdown
                        i18n: true
                - label: 'Three Services Overview Section'
                  name: 'three_services'
                  widget: object
                  i18n: true
                  fields:
                      - label: 'Description'
                        name: 'description'
                        widget: markdown
                        i18n: true
                      - label: 'Service Names'
                        name: 'service_names'
                        widget: list
                        i18n: duplicate
                        allow_add: false
                        fields:
                            - label: 'Name'
                              name: 'name'
                              widget: string
                              i18n: true
                            - label: 'Name - Mobile'
                              name: 'name_mobile'
                              widget: string
                              i18n: true
                - label: 'Service Sections'
                  name: 'service_names'
                  widget: list
                  i18n: duplicate
                  # allow_add: false
                  fields:
                      - label: 'Title'
                        name: 'title'
                        widget: string
                        i18n: true
                      - label: 'Title - Mobile'
                        name: 'title_mobile'
                        widget: string
                        i18n: true
                      - label: 'Description'
                        name: 'description'
                        widget: markdown
                        i18n: true
                      - label: 'Sub-Service Names'
                        name: 'sub_service_names'
                        widget: list
                        i18n: duplicate
                        # allow_add: false
                        fields:
                            - label: 'Name'
                              name: 'name'
                              widget: string
                              i18n: true
                            - label: 'Name - Mobile'
                              name: 'name_mobile'
                              widget: string
                              i18n: true
                      - label: 'Photo Credit'
                        name: 'photo_credit'
                        widget: markdown
                        i18n: true
          - name: 'about'
            label: 'About Page'
            file: 'content/about/index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'SEO metatag - description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                      hint: 'not visible on the page, shown on browser tab & in search results',
                  }
                - label: 'Header'
                  name: 'header'
                  widget: object
                  i18n: true
                  fields:
                      - label: 'Page Header'
                        name: 'page_header'
                        widget: 'text'
                        i18n: true
                      - label: 'Header Photo Left'
                        name: 'header_photo_left'
                        widget: image
                        choose_url: false
                        i18n: duplicate
                      - label: 'Header Photo Left (Alt Text)'
                        name: 'header_photo_left_alt'
                        widget: string
                        i18n: true
                      - label: 'Header Photo Right'
                        name: 'header_photo_right'
                        widget: image
                        choose_url: false
                        i18n: duplicate
                      - label: 'Header Photo Right (Alt Text)'
                        name: 'header_photo_right_alt'
                        widget: string
                        i18n: true
                      - label: 'Header Photo Mobile'
                        name: 'header_photo_mobile'
                        widget: image
                        choose_url: false
                        i18n: duplicate
                      - label: 'Header Photo Mobile (Alt Text)'
                        name: 'header_photo_mobile_alt'
                        widget: string
                        i18n: true
                - label: 'Sections'
                  name: 'sections'
                  widget: list
                  i18n: duplicate
                  types:
                      - label: 'Text'
                        name: 'text'
                        widget: object
                        i18n: true
                        fields:
                            - label: 'Text'
                              name: 'text'
                              widget: markdown
                              i18n: true
                            - label: 'Layout'
                              name: 'layout'
                              widget: select
                              i18n: duplicate
                              options:
                                  - { label: 'Process', value: 'process' }
                                  - {
                                        label: 'Specializations 1',
                                        value: 'spec-1',
                                    }
                                  - {
                                        label: 'Specializations 2',
                                        value: 'spec-2',
                                    }
                                  - { label: 'IFS', value: 'ifs' }
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        fields:
                            - label: 'Image'
                              name: 'image'
                              widget: image
                              i18n: duplicate
                            - label: 'Image Alt Text'
                              name: 'image_alt'
                              widget: string
                              i18n: true
                            - label: 'Layout'
                              name: 'layout'
                              widget: select
                              i18n: duplicate
                              options:
                                  - { label: 'Process', value: 'process' }
                                  - {
                                        label: 'Specializations 1',
                                        value: 'spec-1',
                                    }
                - label: 'Certifications'
                  name: 'certifications'
                  widget: list
                  i18n: duplicate
                  field:
                      label: 'Text: header and bulleted list'
                      name: 'text'
                      i18n: true
                      widget: markdown
          - name: 'services'
            label: 'Services Page'
            file: 'content/services/index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }
          - name: 'contact'
            label: 'Contact Page'
            file: 'content/contact/index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Email',
                      name: 'email',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Phone',
                      name: 'phone',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Address',
                      name: 'address',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }
