backend:
    name: github
    repo: andr-ew/soulcenter-web # Path to your GitHub repository
    branch: main

media_folder: 'static/images'
public_folder: '/images'

i18n:
    structure: multiple_files
    locales: [en, es]
    default_locale: en
collections:
    - name: 'pages'
      label: 'Pages'
      i18n:
          structure: multiple_files
          locales: [en, es]
          default_locale: en
      files:
          - label: 'Homepage'
            name: 'homepage'
            file: 'content/_index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Hero Title',
                      name: 'hero_title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Hero Subtitle',
                      name: 'hero_subtitle',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }
          - name: 'about'
            label: 'About Page'
            file: 'content/about/_index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'SEO metatag - description - not visible',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - label: 'Header'
                  name: 'header'
                  widget: object
                  i18n: true
                  fields:
                      - label: 'Page Header'
                        name: 'page_header'
                        widget: 'text'
                        i18n: true
                      - label: 'Header Photo Left'
                        name: 'header_photo_left'
                        widget: image
                        choose_url: false
                      - label: 'Header Photo Right'
                        name: 'header_photo_right'
                        widget: image
                        choose_url: false
                - label: 'Sections'
                  name: 'sections'
                  widget: list
                  i18n: duplicate
                  types:
                      - label: 'Text'
                        name: 'text'
                        widget: object
                        i18n: true
                        fields:
                            - label: 'Text'
                              name: 'text'
                              widget: markdown
                              i18n: true
                            - label: 'Layout'
                              name: 'layout'
                              widget: select
                              options:
                                  [
                                      'Process',
                                      'Specializations 1',
                                      'Specializations 2',
                                      'IFS',
                                  ]
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        fields:
                            - label: 'Image'
                              name: 'image'
                              widget: image
                            - label: 'Layout'
                              name: 'layout'
                              widget: select
                              options: ['Process', 'Specializations 1']
                - label: 'Certifications'
                  name: 'certifications'
                  widget: list
                  i18n: true
                  field:
                      label: 'Text: header and bulleted list'
                      name: 'text'
                      i18n: true
                      widget: markdown
          - name: 'services'
            label: 'Services Page'
            file: 'content/services/_index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }
          - name: 'contact'
            label: 'Contact Page'
            file: 'content/contact/_index.{{locale}}.md'
            i18n: true
            fields:
                - {
                      label: 'Title',
                      name: 'title',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Email',
                      name: 'email',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Phone',
                      name: 'phone',
                      widget: 'string',
                      i18n: true,
                  }
                - {
                      label: 'Address',
                      name: 'address',
                      widget: 'text',
                      i18n: true,
                  }
                - {
                      label: 'Body',
                      name: 'body',
                      widget: 'markdown',
                      i18n: true,
                  }
